{"abstract":[{"type":"text","text":"Welcome to DSKIT, the SDK developers love"}],"sections":[],"variants":[{"paths":["\/documentation\/dskit"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/dskit"]}],"metadata":{"role":"collection","roleHeading":"Framework","symbolKind":"module","modules":[{"name":"DSKit"}],"externalID":"DSKit","title":"DSKit"},"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","text":"Overview","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"DSKit is a simple ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"Design System Kit"}]},{"text":"  for ","type":"text"},{"type":"strong","inlineContent":[{"type":"text","text":"iOS 15+ SwiftUI"}]},{"type":"text","text":", designed to help developers create simple, consistent and attractive user interfaces with ease. It includes essential view modifiers which ensure that all UI components follow a unified style guide."}]}]}],"kind":"symbol","topicSections":[{"title":"Classes","identifiers":["doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/BlueAppearance","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSFonts","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSScaledFont","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSTextFieldValue","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DarkAppearance","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/KeyboardObserver","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/PeachAppearance","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/RetroAppearance"]},{"identifiers":["doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DPaddingsProtocol","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSAppearance","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSButtonAppearanceProtocol","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSDesignable","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSFontsProtocol","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSNavigationBarAppearanceProtocol","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSPriceAppearanceProtocol","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSSpacingProtocol","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSTabBarAppearanceProtocol","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSTextAppearanceProtocol","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSTextFieldAppearanceProtocol","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSViewAppearanceProtocol"],"title":"Protocols"},{"identifiers":["doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/BlurredBackgroundView","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSBackgroundModifier","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSBlurBackgroundModifier","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSBottomContainer","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSButton","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSButtonAppearance","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSCardStyleModifier","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSChevronView","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSContentMarginKey","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSContentMarginModifier","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSCornerRadiusModifier","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSCoverFlow","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSCustomBackgroundModifier","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSDebugLayoutModifier","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSDebuggableModifier","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSDesignGuideView","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSDesignGuideViewModifier","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSDivider","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSGrid","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSGroupedList","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSHScroll","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSHStack","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSHeightModifier","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSHideKeyboardWhenTappedModifier","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSImage","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSImageView","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSKeyboardAwareModifier","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSKitAppearance","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSMaxWidthCenteredModifier","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSNavigationBarAppearance","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSOnTapModifier","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSPaddingModifier","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSPaddingSystem","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSParentPaddingKey","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSPickerView","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSPreview","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSPreviewForEachAppearance","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSPrice","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSPriceAppearance","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSPriceView","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSQuantityPicker","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSRadioPickerView","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSRatingView","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSSFSymbolButton","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSScreen","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSScreenModifier","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSScrollableContentMarginKey","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSSecondaryBackgroundModifier","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSSectionHeaderView","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSSectionStyleModifier","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSSelectedStyleModifier","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSShadowModifier","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSSize","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSSizeModifier","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSSpacingSystem","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSTabbarAppearance","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSTermsAndConditions","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSText","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSTextAppearance","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSTextField","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSTextFieldAppearance","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSTextFieldColors","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSToolbarSFSymbolButton","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSVStack","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSViewAppearance","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSWidthModifier","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/PickerViewGrid","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/PickerViewHorizontal","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/RadioPickerViewDemo","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/TestableDSHStack","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/TestableDSVStack"],"title":"Structures"},{"identifiers":["doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSButtonColorKey","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSColorKey","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSContentMode","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSDimension","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSDisplayShape","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSImageContentType","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSNavigationBarColor","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSPadding","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSPriceColorKey","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSSpace","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSTabBarColorKey","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSTextColorKey","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSTextFieldColorKey","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSTextFontKey","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSTextStyle","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSViewColorKey","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSViewStyle"],"title":"Enumerations"}],"hierarchy":{"paths":[[]]},"references":{"doc://dskit.app.DSKit/documentation/DSKit/DSBlurBackgroundModifier":{"url":"\/documentation\/dskit\/dsblurbackgroundmodifier","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSBlurBackgroundModifier","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DSBlurBackgroundModifier"}],"title":"DSBlurBackgroundModifier","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSBlurBackgroundModifier","role":"symbol","kind":"symbol","type":"topic"},"doc://dskit.app.DSKit/documentation/DSKit/DSBackgroundModifier":{"type":"topic","title":"DSBackgroundModifier","kind":"symbol","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSBackgroundModifier","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"DSBackgroundModifier","kind":"identifier"}],"url":"\/documentation\/dskit\/dsbackgroundmodifier","navigatorTitle":[{"text":"DSBackgroundModifier","kind":"identifier"}],"role":"symbol"},"doc://dskit.app.DSKit/documentation/DSKit/DSTextFieldAppearance":{"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSTextFieldAppearance","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSTextFieldAppearance"}],"kind":"symbol","abstract":[],"title":"DSTextFieldAppearance","navigatorTitle":[{"text":"DSTextFieldAppearance","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/dskit\/dstextfieldappearance"},"doc://dskit.app.DSKit/documentation/DSKit":{"type":"topic","url":"\/documentation\/dskit","role":"collection","kind":"symbol","title":"DSKit","abstract":[{"type":"text","text":"Welcome to DSKIT, the SDK developers love"}],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit"},"doc://dskit.app.DSKit/documentation/DSKit/DSImageView":{"type":"topic","title":"DSImageView","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSImageView"}],"url":"\/documentation\/dskit\/dsimageview","abstract":[],"navigatorTitle":[{"text":"DSImageView","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSImageView","role":"symbol"},"doc://dskit.app.DSKit/documentation/DSKit/DSCustomBackgroundModifier":{"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSCustomBackgroundModifier","navigatorTitle":[{"kind":"identifier","text":"DSCustomBackgroundModifier"}],"abstract":[],"type":"topic","kind":"symbol","title":"DSCustomBackgroundModifier","url":"\/documentation\/dskit\/dscustombackgroundmodifier","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSCustomBackgroundModifier","kind":"identifier"}]},"doc://dskit.app.DSKit/documentation/DSKit/KeyboardObserver":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"KeyboardObserver","kind":"identifier"}],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/KeyboardObserver","role":"symbol","kind":"symbol","url":"\/documentation\/dskit\/keyboardobserver","title":"KeyboardObserver","abstract":[],"navigatorTitle":[{"text":"KeyboardObserver","kind":"identifier"}],"type":"topic"},"doc://dskit.app.DSKit/documentation/DSKit/DSDebuggableModifier":{"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSDebuggableModifier","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSDebuggableModifier"}],"kind":"symbol","abstract":[],"title":"DSDebuggableModifier","navigatorTitle":[{"text":"DSDebuggableModifier","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/dskit\/dsdebuggablemodifier"},"doc://dskit.app.DSKit/documentation/DSKit/DSKitAppearance":{"url":"\/documentation\/dskit\/dskitappearance","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSKitAppearance"}],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSKitAppearance","kind":"symbol","type":"topic","role":"symbol","title":"DSKitAppearance","navigatorTitle":[{"text":"DSKitAppearance","kind":"identifier"}]},"doc://dskit.app.DSKit/documentation/DSKit/DSGroupedList":{"abstract":[],"url":"\/documentation\/dskit\/dsgroupedlist","type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSGroupedList","kind":"identifier"}],"kind":"symbol","title":"DSGroupedList","role":"symbol","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSGroupedList","navigatorTitle":[{"kind":"identifier","text":"DSGroupedList"}]},"doc://dskit.app.DSKit/documentation/DSKit/DSRadioPickerView":{"url":"\/documentation\/dskit\/dsradiopickerview","title":"DSRadioPickerView","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"DSRadioPickerView","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSRadioPickerView","navigatorTitle":[{"kind":"identifier","text":"DSRadioPickerView"}],"type":"topic","abstract":[]},"doc://dskit.app.DSKit/documentation/DSKit/DSDesignable":{"title":"DSDesignable","role":"symbol","url":"\/documentation\/dskit\/dsdesignable","type":"topic","abstract":[],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSDesignable","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DSDesignable","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DSDesignable"}]},"doc://dskit.app.DSKit/documentation/DSKit/DSChevronView":{"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSChevronView","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DSChevronView"}],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSChevronView","title":"DSChevronView","url":"\/documentation\/dskit\/dschevronview","abstract":[]},"doc://dskit.app.DSKit/documentation/DSKit/DSToolbarSFSymbolButton":{"abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSToolbarSFSymbolButton"}],"kind":"symbol","title":"DSToolbarSFSymbolButton","navigatorTitle":[{"kind":"identifier","text":"DSToolbarSFSymbolButton"}],"url":"\/documentation\/dskit\/dstoolbarsfsymbolbutton","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSToolbarSFSymbolButton","type":"topic","role":"symbol"},"doc://dskit.app.DSKit/documentation/DSKit/DSImage":{"abstract":[],"url":"\/documentation\/dskit\/dsimage","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSImage"}],"navigatorTitle":[{"text":"DSImage","kind":"identifier"}],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSImage","type":"topic","kind":"symbol","title":"DSImage","role":"symbol"},"doc://dskit.app.DSKit/documentation/DSKit/DSPaddingModifier":{"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSPaddingModifier","navigatorTitle":[{"text":"DSPaddingModifier","kind":"identifier"}],"type":"topic","kind":"symbol","title":"DSPaddingModifier","abstract":[],"url":"\/documentation\/dskit\/dspaddingmodifier","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSPaddingModifier","kind":"identifier"}]},"doc://dskit.app.DSKit/documentation/DSKit/DSScreenModifier":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DSScreenModifier"}],"kind":"symbol","title":"DSScreenModifier","abstract":[],"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSScreenModifier","kind":"identifier"}],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSScreenModifier","url":"\/documentation\/dskit\/dsscreenmodifier"},"doc://dskit.app.DSKit/documentation/DSKit/DSPreviewForEachAppearance":{"navigatorTitle":[{"text":"DSPreviewForEachAppearance","kind":"identifier"}],"url":"\/documentation\/dskit\/dspreviewforeachappearance","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSPreviewForEachAppearance"}],"abstract":[],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSPreviewForEachAppearance","type":"topic","title":"DSPreviewForEachAppearance","role":"symbol","kind":"symbol"},"doc://dskit.app.DSKit/documentation/DSKit/DSTermsAndConditions":{"abstract":[],"type":"topic","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSTermsAndConditions","kind":"symbol","url":"\/documentation\/dskit\/dstermsandconditions","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSTermsAndConditions","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DSTermsAndConditions"}],"title":"DSTermsAndConditions"},"doc://dskit.app.DSKit/documentation/DSKit/DSSectionStyleModifier":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSSectionStyleModifier"}],"navigatorTitle":[{"kind":"identifier","text":"DSSectionStyleModifier"}],"kind":"symbol","abstract":[],"type":"topic","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSSectionStyleModifier","url":"\/documentation\/dskit\/dssectionstylemodifier","title":"DSSectionStyleModifier","role":"symbol"},"doc://dskit.app.DSKit/documentation/DSKit/DSTextFieldValue":{"type":"topic","abstract":[],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSTextFieldValue","kind":"symbol","url":"\/documentation\/dskit\/dstextfieldvalue","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSTextFieldValue"}],"navigatorTitle":[{"text":"DSTextFieldValue","kind":"identifier"}],"title":"DSTextFieldValue"},"doc://dskit.app.DSKit/documentation/DSKit/DSParentPaddingKey":{"type":"topic","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSParentPaddingKey","kind":"identifier"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSParentPaddingKey","url":"\/documentation\/dskit\/dsparentpaddingkey","kind":"symbol","navigatorTitle":[{"text":"DSParentPaddingKey","kind":"identifier"}],"title":"DSParentPaddingKey"},"doc://dskit.app.DSKit/documentation/DSKit/DSNavigationBarColor":{"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"DSNavigationBarColor"}],"title":"DSNavigationBarColor","role":"symbol","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSNavigationBarColor","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSNavigationBarColor","kind":"identifier"}],"url":"\/documentation\/dskit\/dsnavigationbarcolor"},"doc://dskit.app.DSKit/documentation/DSKit/DSViewStyle":{"abstract":[],"kind":"symbol","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSViewStyle","type":"topic","url":"\/documentation\/dskit\/dsviewstyle","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSViewStyle"}],"navigatorTitle":[{"text":"DSViewStyle","kind":"identifier"}],"role":"symbol","title":"DSViewStyle"},"doc://dskit.app.DSKit/documentation/DSKit/DSPriceColorKey":{"type":"topic","title":"DSPriceColorKey","kind":"symbol","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSPriceColorKey","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSPriceColorKey","kind":"identifier"}],"url":"\/documentation\/dskit\/dspricecolorkey","navigatorTitle":[{"text":"DSPriceColorKey","kind":"identifier"}],"role":"symbol"},"doc://dskit.app.DSKit/documentation/DSKit/DSButtonAppearance":{"abstract":[],"url":"\/documentation\/dskit\/dsbuttonappearance","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DSButtonAppearance"}],"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSButtonAppearance"}],"kind":"symbol","title":"DSButtonAppearance","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSButtonAppearance","type":"topic"},"doc://dskit.app.DSKit/documentation/DSKit/DSTextStyle":{"type":"topic","title":"DSTextStyle","kind":"symbol","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSTextStyle","abstract":[],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DSTextStyle","kind":"identifier"}],"url":"\/documentation\/dskit\/dstextstyle","navigatorTitle":[{"kind":"identifier","text":"DSTextStyle"}],"role":"symbol"},"doc://dskit.app.DSKit/documentation/DSKit/DSSize":{"type":"topic","title":"DSSize","kind":"symbol","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSSize","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSSize"}],"url":"\/documentation\/dskit\/dssize","navigatorTitle":[{"text":"DSSize","kind":"identifier"}],"role":"symbol"},"doc://dskit.app.DSKit/documentation/DSKit/DSViewAppearance":{"navigatorTitle":[{"text":"DSViewAppearance","kind":"identifier"}],"url":"\/documentation\/dskit\/dsviewappearance","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSViewAppearance"}],"abstract":[],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSViewAppearance","type":"topic","title":"DSViewAppearance","role":"symbol","kind":"symbol"},"doc://dskit.app.DSKit/documentation/DSKit/DPaddingsProtocol":{"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DPaddingsProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DPaddingsProtocol"}],"kind":"symbol","abstract":[],"title":"DPaddingsProtocol","navigatorTitle":[{"text":"DPaddingsProtocol","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/dskit\/dpaddingsprotocol"},"doc://dskit.app.DSKit/documentation/DSKit/DSDesignGuideViewModifier":{"title":"DSDesignGuideViewModifier","role":"symbol","url":"\/documentation\/dskit\/dsdesignguideviewmodifier","type":"topic","abstract":[],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSDesignGuideViewModifier","kind":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"DSDesignGuideViewModifier","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DSDesignGuideViewModifier"}]},"doc://dskit.app.DSKit/documentation/DSKit/DSViewColorKey":{"abstract":[],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSViewColorKey","navigatorTitle":[{"text":"DSViewColorKey","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dskit\/dsviewcolorkey","type":"topic","title":"DSViewColorKey","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSViewColorKey","kind":"identifier"}]},"doc://dskit.app.DSKit/documentation/DSKit/DSContentMode":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DSContentMode","kind":"identifier"}],"navigatorTitle":[{"text":"DSContentMode","kind":"identifier"}],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSContentMode","kind":"symbol","abstract":[],"url":"\/documentation\/dskit\/dscontentmode","type":"topic","title":"DSContentMode","role":"symbol"},"doc://dskit.app.DSKit/documentation/DSKit/DSFontsProtocol":{"type":"topic","title":"DSFontsProtocol","kind":"symbol","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSFontsProtocol","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSFontsProtocol","kind":"identifier"}],"url":"\/documentation\/dskit\/dsfontsprotocol","navigatorTitle":[{"text":"DSFontsProtocol","kind":"identifier"}],"role":"symbol"},"doc://dskit.app.DSKit/documentation/DSKit/DSContentMarginKey":{"type":"topic","abstract":[],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSContentMarginKey","title":"DSContentMarginKey","role":"symbol","kind":"symbol","url":"\/documentation\/dskit\/dscontentmarginkey","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSContentMarginKey"}],"navigatorTitle":[{"text":"DSContentMarginKey","kind":"identifier"}]},"doc://dskit.app.DSKit/documentation/DSKit/DSSectionHeaderView":{"navigatorTitle":[{"text":"DSSectionHeaderView","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSSectionHeaderView","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSSectionHeaderView","kind":"identifier"}],"title":"DSSectionHeaderView","type":"topic","abstract":[],"url":"\/documentation\/dskit\/dssectionheaderview"},"doc://dskit.app.DSKit/documentation/DSKit/DSSpace":{"title":"DSSpace","role":"symbol","url":"\/documentation\/dskit\/dsspace","type":"topic","abstract":[],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSSpace","kind":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSSpace"}],"navigatorTitle":[{"text":"DSSpace","kind":"identifier"}]},"doc://dskit.app.DSKit/documentation/DSKit/DSTextField":{"title":"DSTextField","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSTextField"}],"kind":"symbol","navigatorTitle":[{"text":"DSTextField","kind":"identifier"}],"url":"\/documentation\/dskit\/dstextfield","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSTextField","type":"topic","abstract":[]},"doc://dskit.app.DSKit/documentation/DSKit/DSTextFieldColors":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSTextFieldColors","kind":"identifier"}],"title":"DSTextFieldColors","kind":"symbol","role":"symbol","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSTextFieldColors","url":"\/documentation\/dskit\/dstextfieldcolors","navigatorTitle":[{"kind":"identifier","text":"DSTextFieldColors"}],"type":"topic","abstract":[]},"doc://dskit.app.DSKit/documentation/DSKit/DSTextAppearance":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSTextAppearance"}],"type":"topic","title":"DSTextAppearance","kind":"symbol","abstract":[],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSTextAppearance","url":"\/documentation\/dskit\/dstextappearance","navigatorTitle":[{"kind":"identifier","text":"DSTextAppearance"}],"role":"symbol"},"doc://dskit.app.DSKit/documentation/DSKit/DSViewAppearanceProtocol":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"DSViewAppearanceProtocol","kind":"identifier"}],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSViewAppearanceProtocol","role":"symbol","kind":"symbol","url":"\/documentation\/dskit\/dsviewappearanceprotocol","title":"DSViewAppearanceProtocol","abstract":[],"navigatorTitle":[{"text":"DSViewAppearanceProtocol","kind":"identifier"}],"type":"topic"},"doc://dskit.app.DSKit/documentation/DSKit/DSQuantityPicker":{"url":"\/documentation\/dskit\/dsquantitypicker","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSQuantityPicker","kind":"symbol","abstract":[],"role":"symbol","navigatorTitle":[{"text":"DSQuantityPicker","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"DSQuantityPicker","kind":"identifier"}],"title":"DSQuantityPicker"},"doc://dskit.app.DSKit/documentation/DSKit/DSTabBarColorKey":{"type":"topic","abstract":[],"title":"DSTabBarColorKey","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSTabBarColorKey","role":"symbol","kind":"symbol","url":"\/documentation\/dskit\/dstabbarcolorkey","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSTabBarColorKey","kind":"identifier"}],"navigatorTitle":[{"text":"DSTabBarColorKey","kind":"identifier"}]},"doc://dskit.app.DSKit/documentation/DSKit/DSKeyboardAwareModifier":{"abstract":[],"url":"\/documentation\/dskit\/dskeyboardawaremodifier","navigatorTitle":[{"text":"DSKeyboardAwareModifier","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"DSKeyboardAwareModifier","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSKeyboardAwareModifier","title":"DSKeyboardAwareModifier"},"doc://dskit.app.DSKit/documentation/DSKit/DSScaledFont":{"type":"topic","abstract":[{"type":"text","text":"A utility class to help you use custom fonts with"},{"text":" ","type":"text"},{"type":"text","text":"dynamic type."}],"title":"DSScaledFont","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSScaledFont","role":"symbol","kind":"symbol","url":"\/documentation\/dskit\/dsscaledfont","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSScaledFont","kind":"identifier"}],"navigatorTitle":[{"text":"DSScaledFont","kind":"identifier"}]},"doc://dskit.app.DSKit/documentation/DSKit/DarkAppearance":{"kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DarkAppearance","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DarkAppearance"}],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DarkAppearance","title":"DarkAppearance","url":"\/documentation\/dskit\/darkappearance","abstract":[]},"doc://dskit.app.DSKit/documentation/DSKit/DSHideKeyboardWhenTappedModifier":{"type":"topic","abstract":[],"title":"DSHideKeyboardWhenTappedModifier","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSHideKeyboardWhenTappedModifier","role":"symbol","kind":"symbol","url":"\/documentation\/dskit\/dshidekeyboardwhentappedmodifier","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSHideKeyboardWhenTappedModifier"}],"navigatorTitle":[{"text":"DSHideKeyboardWhenTappedModifier","kind":"identifier"}]},"doc://dskit.app.DSKit/documentation/DSKit/DSScrollableContentMarginKey":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSScrollableContentMarginKey","kind":"identifier"}],"url":"\/documentation\/dskit\/dsscrollablecontentmarginkey","title":"DSScrollableContentMarginKey","type":"topic","navigatorTitle":[{"text":"DSScrollableContentMarginKey","kind":"identifier"}],"role":"symbol","abstract":[],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSScrollableContentMarginKey","kind":"symbol"},"doc://dskit.app.DSKit/documentation/DSKit/TestableDSHStack":{"role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"TestableDSHStack"}],"kind":"symbol","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/TestableDSHStack","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TestableDSHStack","kind":"identifier"}],"title":"TestableDSHStack","url":"\/documentation\/dskit\/testabledshstack"},"doc://dskit.app.DSKit/documentation/DSKit/PickerViewGrid":{"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/PickerViewGrid","type":"topic","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PickerViewGrid"}],"navigatorTitle":[{"text":"PickerViewGrid","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dskit\/pickerviewgrid","title":"PickerViewGrid","abstract":[]},"doc://dskit.app.DSKit/documentation/DSKit/DSSpacingSystem":{"abstract":[],"role":"symbol","navigatorTitle":[{"text":"DSSpacingSystem","kind":"identifier"}],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSSpacingSystem"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSSpacingSystem","title":"DSSpacingSystem","url":"\/documentation\/dskit\/dsspacingsystem"},"doc://dskit.app.DSKit/documentation/DSKit/BlueAppearance":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"BlueAppearance"}],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/BlueAppearance","role":"symbol","kind":"symbol","url":"\/documentation\/dskit\/blueappearance","title":"BlueAppearance","abstract":[],"navigatorTitle":[{"text":"BlueAppearance","kind":"identifier"}],"type":"topic"},"doc://dskit.app.DSKit/documentation/DSKit/DSShadowModifier":{"kind":"symbol","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSShadowModifier"}],"type":"topic","role":"symbol","title":"DSShadowModifier","url":"\/documentation\/dskit\/dsshadowmodifier","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSShadowModifier","navigatorTitle":[{"kind":"identifier","text":"DSShadowModifier"}]},"doc://dskit.app.DSKit/documentation/DSKit/DSPreview":{"url":"\/documentation\/dskit\/dspreview","title":"DSPreview","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSPreview"}],"role":"symbol","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSPreview","navigatorTitle":[{"kind":"identifier","text":"DSPreview"}],"type":"topic","abstract":[]},"doc://dskit.app.DSKit/documentation/DSKit/DSHStack":{"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSHStack","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"DSHStack","kind":"identifier"}],"title":"DSHStack","kind":"symbol","role":"symbol","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSHStack","abstract":[],"url":"\/documentation\/dskit\/dshstack"},"doc://dskit.app.DSKit/documentation/DSKit/DSKitVersionString":{"type":"topic","abstract":[{"type":"text","text":"Project version string for DSKit."}],"title":"DSKitVersionString","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSKitVersionString","role":"symbol","kind":"symbol","url":"\/documentation\/dskit\/dskitversionstring","fragments":[{"kind":"identifier","text":"DSKitVersionString"}]},"doc://dskit.app.DSKit/documentation/DSKit/DSDisplayShape":{"kind":"symbol","title":"DSDisplayShape","navigatorTitle":[{"text":"DSDisplayShape","kind":"identifier"}],"role":"symbol","type":"topic","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSDisplayShape","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSDisplayShape","kind":"identifier"}],"url":"\/documentation\/dskit\/dsdisplayshape","abstract":[]},"doc://dskit.app.DSKit/documentation/DSKit/DSRatingView":{"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSRatingView","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSRatingView","kind":"identifier"}],"title":"DSRatingView","url":"\/documentation\/dskit\/dsratingview","navigatorTitle":[{"kind":"identifier","text":"DSRatingView"}],"kind":"symbol","abstract":[],"type":"topic"},"doc://dskit.app.DSKit/documentation/DSKit/DSSpacingProtocol":{"kind":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSSpacingProtocol"}],"type":"topic","role":"symbol","title":"DSSpacingProtocol","url":"\/documentation\/dskit\/dsspacingprotocol","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSSpacingProtocol","navigatorTitle":[{"text":"DSSpacingProtocol","kind":"identifier"}]},"doc://dskit.app.DSKit/documentation/DSKit/DSButton":{"type":"topic","title":"DSButton","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSButton"}],"url":"\/documentation\/dskit\/dsbutton","abstract":[],"navigatorTitle":[{"text":"DSButton","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSButton","role":"symbol"},"doc://dskit.app.DSKit/documentation/DSKit/DSOnTapModifier":{"kind":"symbol","abstract":[],"fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSOnTapModifier"}],"type":"topic","role":"symbol","title":"DSOnTapModifier","url":"\/documentation\/dskit\/dsontapmodifier","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSOnTapModifier","navigatorTitle":[{"text":"DSOnTapModifier","kind":"identifier"}]},"doc://dskit.app.DSKit/documentation/DSKit/DSButtonColorKey":{"kind":"symbol","title":"DSButtonColorKey","navigatorTitle":[{"kind":"identifier","text":"DSButtonColorKey"}],"url":"\/documentation\/dskit\/dsbuttoncolorkey","abstract":[],"role":"symbol","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSButtonColorKey","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DSButtonColorKey","kind":"identifier"}],"type":"topic"},"doc://dskit.app.DSKit/documentation/DSKit/DSPickerView":{"url":"\/documentation\/dskit\/dspickerview","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSPickerView","role":"symbol","navigatorTitle":[{"text":"DSPickerView","kind":"identifier"}],"type":"topic","title":"DSPickerView","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSPickerView","kind":"identifier"}],"abstract":[],"kind":"symbol"},"doc://dskit.app.DSKit/documentation/DSKit/DSPadding":{"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSPadding","navigatorTitle":[{"text":"DSPadding","kind":"identifier"}],"type":"topic","kind":"symbol","title":"DSPadding","abstract":[],"url":"\/documentation\/dskit\/dspadding","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"DSPadding","kind":"identifier"}]},"doc://dskit.app.DSKit/documentation/DSKit/DSImageContentType":{"abstract":[],"type":"topic","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSImageContentType","kind":"symbol","url":"\/documentation\/dskit\/dsimagecontenttype","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"DSImageContentType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DSImageContentType"}],"title":"DSImageContentType"},"doc://dskit.app.DSKit/documentation/DSKit/DSTextFieldColorKey":{"type":"topic","kind":"symbol","navigatorTitle":[{"text":"DSTextFieldColorKey","kind":"identifier"}],"abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSTextFieldColorKey","kind":"identifier"}],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSTextFieldColorKey","role":"symbol","url":"\/documentation\/dskit\/dstextfieldcolorkey","title":"DSTextFieldColorKey"},"doc://dskit.app.DSKit/documentation/DSKit/DSBottomContainer":{"abstract":[],"type":"topic","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSBottomContainer","kind":"symbol","url":"\/documentation\/dskit\/dsbottomcontainer","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSBottomContainer"}],"navigatorTitle":[{"kind":"identifier","text":"DSBottomContainer"}],"role":"symbol","title":"DSBottomContainer"},"doc://dskit.app.DSKit/documentation/DSKit/DSWidthModifier":{"kind":"symbol","abstract":[{"type":"text","text":"A view modifier that adjusts the width of a view based on "},{"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSDimension","type":"reference","isActive":true},{"type":"text","text":" and current appearance settings."}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSWidthModifier"}],"type":"topic","role":"symbol","title":"DSWidthModifier","url":"\/documentation\/dskit\/dswidthmodifier","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSWidthModifier","navigatorTitle":[{"kind":"identifier","text":"DSWidthModifier"}]},"doc://dskit.app.DSKit/documentation/DSKit/DSTextFontKey":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSTextFontKey","kind":"identifier"}],"navigatorTitle":[{"text":"DSTextFontKey","kind":"identifier"}],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSTextFontKey","kind":"symbol","abstract":[],"url":"\/documentation\/dskit\/dstextfontkey","type":"topic","title":"DSTextFontKey","role":"symbol"},"doc://dskit.app.DSKit/documentation/DSKit/DSTabBarAppearanceProtocol":{"type":"topic","abstract":[],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSTabBarAppearanceProtocol","kind":"symbol","url":"\/documentation\/dskit\/dstabbarappearanceprotocol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSTabBarAppearanceProtocol"}],"navigatorTitle":[{"text":"DSTabBarAppearanceProtocol","kind":"identifier"}],"title":"DSTabBarAppearanceProtocol"},"doc://dskit.app.DSKit/documentation/DSKit/DSDebugLayoutModifier":{"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSDebugLayoutModifier","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSDebugLayoutModifier","kind":"identifier"}],"title":"DSDebugLayoutModifier","kind":"symbol","url":"\/documentation\/dskit\/dsdebuglayoutmodifier","navigatorTitle":[{"kind":"identifier","text":"DSDebugLayoutModifier"}],"type":"topic","role":"symbol","abstract":[]},"doc://dskit.app.DSKit/documentation/DSKit/PeachAppearance":{"url":"\/documentation\/dskit\/peachappearance","navigatorTitle":[{"kind":"identifier","text":"PeachAppearance"}],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/PeachAppearance","title":"PeachAppearance","abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"PeachAppearance","kind":"identifier"}]},"doc://dskit.app.DSKit/documentation/DSKit/DSNavigationBarAppearance":{"title":"DSNavigationBarAppearance","role":"symbol","url":"\/documentation\/dskit\/dsnavigationbarappearance","type":"topic","abstract":[],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSNavigationBarAppearance","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSNavigationBarAppearance"}],"navigatorTitle":[{"kind":"identifier","text":"DSNavigationBarAppearance"}]},"doc://dskit.app.DSKit/documentation/DSKit/DSButtonAppearanceProtocol":{"type":"topic","title":"DSButtonAppearanceProtocol","kind":"symbol","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSButtonAppearanceProtocol","abstract":[],"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSButtonAppearanceProtocol","kind":"identifier"}],"url":"\/documentation\/dskit\/dsbuttonappearanceprotocol","navigatorTitle":[{"text":"DSButtonAppearanceProtocol","kind":"identifier"}],"role":"symbol"},"doc://dskit.app.DSKit/documentation/DSKit/DSFonts":{"type":"topic","title":"DSFonts","kind":"symbol","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSFonts","abstract":[],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSFonts"}],"url":"\/documentation\/dskit\/dsfonts","navigatorTitle":[{"text":"DSFonts","kind":"identifier"}],"role":"symbol"},"doc://dskit.app.DSKit/documentation/DSKit/RetroAppearance":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"RetroAppearance","kind":"identifier"}],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/RetroAppearance","role":"symbol","kind":"symbol","url":"\/documentation\/dskit\/retroappearance","title":"RetroAppearance","abstract":[],"navigatorTitle":[{"text":"RetroAppearance","kind":"identifier"}],"type":"topic"},"doc://dskit.app.DSKit/documentation/DSKit/DSTextColorKey":{"abstract":[],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSTextColorKey","navigatorTitle":[{"text":"DSTextColorKey","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/dskit\/dstextcolorkey","type":"topic","title":"DSTextColorKey","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"DSTextColorKey","kind":"identifier"}]},"doc://dskit.app.DSKit/documentation/DSKit/DSPriceAppearance":{"type":"topic","abstract":[],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSPriceAppearance","title":"DSPriceAppearance","role":"symbol","kind":"symbol","url":"\/documentation\/dskit\/dspriceappearance","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"DSPriceAppearance","kind":"identifier"}],"navigatorTitle":[{"text":"DSPriceAppearance","kind":"identifier"}]},"doc://dskit.app.DSKit/documentation/DSKit/DSSecondaryBackgroundModifier":{"abstract":[],"url":"\/documentation\/dskit\/dssecondarybackgroundmodifier","title":"DSSecondaryBackgroundModifier","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSSecondaryBackgroundModifier","kind":"symbol","role":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"DSSecondaryBackgroundModifier","kind":"identifier"}],"navigatorTitle":[{"text":"DSSecondaryBackgroundModifier","kind":"identifier"}]},"doc://dskit.app.DSKit/documentation/DSKit/DSPriceAppearanceProtocol":{"url":"\/documentation\/dskit\/dspriceappearanceprotocol","navigatorTitle":[{"kind":"identifier","text":"DSPriceAppearanceProtocol"}],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSPriceAppearanceProtocol","title":"DSPriceAppearanceProtocol","abstract":[],"type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"DSPriceAppearanceProtocol","kind":"identifier"}]},"doc://dskit.app.DSKit/documentation/DSKit/DSCardStyleModifier":{"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSCardStyleModifier","navigatorTitle":[{"kind":"identifier","text":"DSCardStyleModifier"}],"kind":"symbol","type":"topic","title":"DSCardStyleModifier","abstract":[],"url":"\/documentation\/dskit\/dscardstylemodifier","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSCardStyleModifier","kind":"identifier"}]},"doc://dskit.app.DSKit/documentation/DSKit/DSHScroll":{"abstract":[],"kind":"symbol","type":"topic","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSHScroll","url":"\/documentation\/dskit\/dshscroll","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSHScroll"}],"navigatorTitle":[{"text":"DSHScroll","kind":"identifier"}],"role":"symbol","title":"DSHScroll"},"doc://dskit.app.DSKit/documentation/DSKit/DSCornerRadiusModifier":{"url":"\/documentation\/dskit\/dscornerradiusmodifier","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSCornerRadiusModifier","navigatorTitle":[{"kind":"identifier","text":"DSCornerRadiusModifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSCornerRadiusModifier"}],"type":"topic","role":"symbol","kind":"symbol","title":"DSCornerRadiusModifier","abstract":[]},"doc://dskit.app.DSKit/documentation/DSKit/DSColorKey":{"type":"topic","title":"DSColorKey","kind":"symbol","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSColorKey","abstract":[],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSColorKey"}],"url":"\/documentation\/dskit\/dscolorkey","navigatorTitle":[{"text":"DSColorKey","kind":"identifier"}],"role":"symbol"},"doc://dskit.app.DSKit/documentation/DSKit/TestableDSVStack":{"kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"TestableDSVStack","kind":"identifier"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"TestableDSVStack","kind":"identifier"}],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/TestableDSVStack","title":"TestableDSVStack","url":"\/documentation\/dskit\/testabledsvstack","abstract":[]},"doc://dskit.app.DSKit/documentation/DSKit/PickerViewHorizontal":{"url":"\/documentation\/dskit\/pickerviewhorizontal","type":"topic","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/PickerViewHorizontal","title":"PickerViewHorizontal","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PickerViewHorizontal"}],"abstract":[],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"PickerViewHorizontal"}]},"doc://dskit.app.DSKit/documentation/DSKit/DSPriceView":{"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSPriceView","url":"\/documentation\/dskit\/dspriceview","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSPriceView"}],"navigatorTitle":[{"text":"DSPriceView","kind":"identifier"}],"abstract":[],"kind":"symbol","title":"DSPriceView","type":"topic"},"doc://dskit.app.DSKit/documentation/DSKit/DSTabbarAppearance":{"type":"topic","abstract":[],"title":"DSTabbarAppearance","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSTabbarAppearance","role":"symbol","kind":"symbol","url":"\/documentation\/dskit\/dstabbarappearance","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSTabbarAppearance","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DSTabbarAppearance"}]},"doc://dskit.app.DSKit/documentation/DSKit/BlurredBackgroundView":{"role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"BlurredBackgroundView","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/BlurredBackgroundView","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"BlurredBackgroundView","kind":"identifier"}],"title":"BlurredBackgroundView","url":"\/documentation\/dskit\/blurredbackgroundview"},"doc://dskit.app.DSKit/documentation/DSKit/DSPaddingSystem":{"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSPaddingSystem","navigatorTitle":[{"kind":"identifier","text":"DSPaddingSystem"}],"kind":"symbol","abstract":[],"type":"topic","title":"DSPaddingSystem","url":"\/documentation\/dskit\/dspaddingsystem","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSPaddingSystem","kind":"identifier"}]},"doc://dskit.app.DSKit/documentation/DSKit/DSKitVersionNumber":{"type":"topic","abstract":[{"type":"text","text":"Project version number for DSKit."}],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSKitVersionNumber","title":"DSKitVersionNumber","role":"symbol","kind":"symbol","url":"\/documentation\/dskit\/dskitversionnumber","fragments":[{"text":"DSKitVersionNumber","kind":"identifier"}]},"doc://dskit.app.DSKit/documentation/DSKit/DSGrid":{"kind":"symbol","type":"topic","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSGrid","navigatorTitle":[{"text":"DSGrid","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"DSGrid","kind":"identifier"}],"role":"symbol","title":"DSGrid","abstract":[],"url":"\/documentation\/dskit\/dsgrid"},"doc://dskit.app.DSKit/documentation/DSKit/DSDivider":{"role":"symbol","navigatorTitle":[{"text":"DSDivider","kind":"identifier"}],"type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"DSDivider","kind":"identifier"}],"title":"DSDivider","kind":"symbol","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSDivider","url":"\/documentation\/dskit\/dsdivider"},"doc://dskit.app.DSKit/documentation/DSKit/DSAppearance":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSAppearance","kind":"identifier"}],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSAppearance","role":"symbol","kind":"symbol","url":"\/documentation\/dskit\/dsappearance","title":"DSAppearance","abstract":[],"navigatorTitle":[{"text":"DSAppearance","kind":"identifier"}],"type":"topic"},"doc://dskit.app.DSKit/documentation/DSKit/DSTextAppearanceProtocol":{"fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSTextAppearanceProtocol"}],"kind":"symbol","title":"DSTextAppearanceProtocol","type":"topic","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSTextAppearanceProtocol","abstract":[],"url":"\/documentation\/dskit\/dstextappearanceprotocol","navigatorTitle":[{"kind":"identifier","text":"DSTextAppearanceProtocol"}],"role":"symbol"},"doc://dskit.app.DSKit/documentation/DSKit/DSVStack":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"DSVStack"}],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSVStack","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"DSVStack","kind":"identifier"}],"type":"topic","abstract":[],"url":"\/documentation\/dskit\/dsvstack","kind":"symbol","title":"DSVStack"},"doc://dskit.app.DSKit/documentation/DSKit/DSCoverFlow":{"kind":"symbol","title":"DSCoverFlow","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSCoverFlow","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DSCoverFlow"}],"abstract":[],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSCoverFlow","type":"topic","url":"\/documentation\/dskit\/dscoverflow","role":"symbol"},"doc://dskit.app.DSKit/documentation/DSKit/DSMaxWidthCenteredModifier":{"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSMaxWidthCenteredModifier","navigatorTitle":[{"text":"DSMaxWidthCenteredModifier","kind":"identifier"}],"abstract":[],"type":"topic","kind":"symbol","title":"DSMaxWidthCenteredModifier","url":"\/documentation\/dskit\/dsmaxwidthcenteredmodifier","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSMaxWidthCenteredModifier"}]},"doc://dskit.app.DSKit/documentation/DSKit/DSSizeModifier":{"kind":"symbol","type":"topic","title":"DSSizeModifier","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"DSSizeModifier","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DSSizeModifier"}],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSSizeModifier","role":"symbol","url":"\/documentation\/dskit\/dssizemodifier","abstract":[]},"doc://dskit.app.DSKit/documentation/DSKit/DSPrice":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSPrice","kind":"identifier"}],"title":"DSPrice","kind":"symbol","role":"symbol","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSPrice","url":"\/documentation\/dskit\/dsprice","navigatorTitle":[{"kind":"identifier","text":"DSPrice"}],"abstract":[],"type":"topic"},"doc://dskit.app.DSKit/documentation/DSKit/DSNavigationBarAppearanceProtocol":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSNavigationBarAppearanceProtocol"}],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSNavigationBarAppearanceProtocol","role":"symbol","kind":"symbol","url":"\/documentation\/dskit\/dsnavigationbarappearanceprotocol","title":"DSNavigationBarAppearanceProtocol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"DSNavigationBarAppearanceProtocol"}],"type":"topic"},"doc://dskit.app.DSKit/documentation/DSKit/DSScreen":{"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSScreen","type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"DSScreen","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DSScreen"}],"kind":"symbol","title":"DSScreen","url":"\/documentation\/dskit\/dsscreen","abstract":[]},"doc://dskit.app.DSKit/documentation/DSKit/DSSFSymbolButton":{"title":"DSSFSymbolButton","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"DSSFSymbolButton","kind":"identifier"}],"kind":"symbol","navigatorTitle":[{"text":"DSSFSymbolButton","kind":"identifier"}],"url":"\/documentation\/dskit\/dssfsymbolbutton","type":"topic","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSSFSymbolButton","abstract":[]},"doc://dskit.app.DSKit/documentation/DSKit/RadioPickerViewDemo":{"title":"RadioPickerViewDemo","abstract":[],"navigatorTitle":[{"text":"RadioPickerViewDemo","kind":"identifier"}],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/RadioPickerViewDemo","url":"\/documentation\/dskit\/radiopickerviewdemo","kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"RadioPickerViewDemo"}],"type":"topic"},"doc://dskit.app.DSKit/documentation/DSKit/DSDimension":{"navigatorTitle":[{"text":"DSDimension","kind":"identifier"}],"role":"symbol","type":"topic","title":"DSDimension","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"DSDimension"}],"abstract":[{"code":"DSDimension","type":"codeVoice"},{"text":" is an enumeration that encapsulates various ways to define dimensions in the DSKit framework. It allows for dimensions to be specified with flexible options, supporting dynamic UI adaptations based on the current appearance settings.","type":"text"}],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSDimension","url":"\/documentation\/dskit\/dsdimension","kind":"symbol"},"doc://dskit.app.DSKit/documentation/DSKit/DSHeightModifier":{"title":"DSHeightModifier","kind":"symbol","url":"\/documentation\/dskit\/dsheightmodifier","type":"topic","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSHeightModifier","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSHeightModifier","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"DSHeightModifier"}],"abstract":[],"role":"symbol"},"doc://dskit.app.DSKit/documentation/DSKit/DSSelectedStyleModifier":{"url":"\/documentation\/dskit\/dsselectedstylemodifier","identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSSelectedStyleModifier","navigatorTitle":[{"kind":"identifier","text":"DSSelectedStyleModifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSSelectedStyleModifier"}],"type":"topic","role":"symbol","kind":"symbol","title":"DSSelectedStyleModifier","abstract":[]},"doc://dskit.app.DSKit/documentation/DSKit/DSContentMarginModifier":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSContentMarginModifier","kind":"identifier"}],"type":"topic","kind":"symbol","title":"DSContentMarginModifier","abstract":[],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSContentMarginModifier","url":"\/documentation\/dskit\/dscontentmarginmodifier","navigatorTitle":[{"text":"DSContentMarginModifier","kind":"identifier"}],"role":"symbol"},"doc://dskit.app.DSKit/documentation/DSKit/DSTextFieldAppearanceProtocol":{"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSTextFieldAppearanceProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSTextFieldAppearanceProtocol"}],"kind":"symbol","abstract":[],"title":"DSTextFieldAppearanceProtocol","navigatorTitle":[{"text":"DSTextFieldAppearanceProtocol","kind":"identifier"}],"role":"symbol","type":"topic","url":"\/documentation\/dskit\/dstextfieldappearanceprotocol"},"doc://dskit.app.DSKit/documentation/DSKit/DSText":{"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSText","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"DSText","kind":"identifier"}],"title":"DSText","kind":"symbol","type":"topic","abstract":[],"role":"symbol","url":"\/documentation\/dskit\/dstext","navigatorTitle":[{"text":"DSText","kind":"identifier"}]},"doc://dskit.app.DSKit/documentation/DSKit/DSDesignGuideView":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"DSDesignGuideView"}],"navigatorTitle":[{"kind":"identifier","text":"DSDesignGuideView"}],"identifier":"doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSDesignGuideView","kind":"symbol","abstract":[],"url":"\/documentation\/dskit\/dsdesignguideview","type":"topic","title":"DSDesignGuideView","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":[{"identifiers":["doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSKitVersionNumber","doc:\/\/dskit.app.DSKit\/documentation\/DSKit\/DSKitVersionString"],"title":"Variables"}],"op":"replace","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"}]}]}